### PR TITLE
DO NOT YELL THE APP NAME

### PR DESCRIPTION
**Pull request by r10s**
WE SHOULD NOT SUPPORT THAT STYLE!

### CODE REVIEW

**Comment by adbenitez** [comment]
WHAT DO YOU MEAN?

**Comment by adbenitez** [comment]
THIS CAN NOT BE ACCEPTED AS IS, THE APP NAME IS ALSO INSIDE THE CODE, MAYBE A CONSEQUENCE OF NOT HAVING AN WEBXDC API TO GET THE CURRENT APP NAME!

**Comment by adbenitez** [comment]
solved in: https://github.com/DeltaZen/Surf/commit/c7621f757fcba66077b1f313d2e81e7476924bca

thanks for the suggestion!

**Comment by r10s** [comment]
YOU'RE WELCOME, DUDE!!!!

**Pull request closed without merging**
